### ISSUE TITLE
워터마크 비율을 조정한다.

### ISSUE THREAD

**Issue by Martin0o0** [Breaking-Dope/breaking-backend#312]
## 상세 내용

- [ ]  워터마크 비율을 조정합니다.
- [ ] 워터마크가 이미지의 해상도 및 비율에 따라 어떤 미디어파일은 작고, 어떤 미디어파일은 크게 찍히기에 크기에 따라 유동적으로 크기를 조정합니다.
- [ ] 예상 로직은  세로 :  * >= 2160, * >=1080, * >= 720, >= 450, >= 360, * >= 180 으로 가로 :  * >= 3840, * >= 1920, * >= 1280, * >=  800, * >=  320로 구분지어 썸네일을 제작할 예정입니다.

**Comment by JinuCheon** [comment]
일단 이슈 닫습니다!
